# Generated by Django 2.1.5 on 2019-01-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingAddress',
            new_name='billingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress',
            new_name='shippingAddress1',
        ),
    ]
